"""updated

Revision ID: 0b0420b273aa
Revises: 
Create Date: 2025-08-01 18:29:45.446002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b0420b273aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('firstname')
        batch_op.drop_column('isadmin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isadmin', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(length=30), nullable=False))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
