"""fix delivery and order relationships

Revision ID: 2e322509325c
Revises: 7ed4f2e52ffe
Create Date: 2025-12-23 06:26:58.929844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e322509325c'
down_revision = '7ed4f2e52ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['order_id'])
        batch_op.drop_constraint('delivery_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'order', ['order_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('delivery_order_id_fkey', 'order', ['order_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
