"""add ingridients and custom meals

Revision ID: d02ab8042dfd
Revises: cebdbd2c4367
Create Date: 2025-12-19 22:46:17.336520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd02ab8042dfd'
down_revision = 'cebdbd2c4367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_meal_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_meal_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=120), nullable=False),
    sa.Column('ingredient_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['custom_meal_id'], ['custom_meal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('payment',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_constraint('fk_store_order_deliver', type_='foreignkey')
        batch_op.drop_column('taken_by')
        batch_op.drop_column('source_store')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('date_',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.alter_column('openinghours',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('mpesa_shortcode',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('ecocash_short_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('store', schema=None) as batch_op:
        batch_op.alter_column('confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('ecocash_short_code',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('mpesa_shortcode',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('openinghours',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('date_',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('product_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.alter_column('product_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_store', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('taken_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_store_order_deliver', 'deliveryguy', ['taken_by'], ['id'])
        batch_op.alter_column('user_email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('payment',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)

    op.drop_table('custom_meal_ingredient')
    op.drop_table('custom_meal')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
